### ISSUE TITLE
Knit Canvas

### ISSUE THREAD

**Issue by melMass** [Psyop/psyop-fabric-exts#1]
Hello,

Thanks, for those, nice reference for learning.
Do you plan on releasing your **"Knit"** block seen at **s16** ? 💯 

Thanks

**Comment by TKCM** [comment]
Hello melMass.

Thank you for message.
What things "Knit block seen at s16"?

**Comment by melMass** [comment]
I meant the Knitting (cloth fibers) system you showed at SIGGRAPH 2016 :) ?

**Comment by TKCM** [comment]
Sorry I am not an official of Psyop.
I received the wrong e-mail from gitHub.

**Comment by jonahfriedman** [comment]
Hi MelMass,

Thanks, I hope you find what we've released useful. About the Entwiner (knit system), we aren't planning to release it at this time.

**Comment by TKCM** [comment]
Hello jonahfriedman.

I received the e-mail that about this issue from github. and now too.
I misunderstanding, and wrote a comment and then turned it off.

I don't know why that I recieved it.

**Comment by melMass** [comment]
No problem thanks for letting me know, the tool looks great, I've managed similar setup in VEX which works great, but would have loved to see how you dealt with common issues procedurally in Fabric.
